import type { Metadata } from "next";
import { Inter } from "next/font/google";


import { NavBar } from "./components/NavBar/NavBar";
import { NextAuthProvider } from "./Provider";
import { ReduxProvider } from "./storeProvider/storeProvider";
import { Footer } from "./components/Footer/Footer";

import "./globals.css";
import "animate.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark bg-primary">
      <body className={inter.className}>
        <NextAuthProvider>
          <ReduxProvider>
            <div className="max-w-screen-xl mx-auto h-full flex flex-col min-h-[100vh]">
              <NavBar />
              {children}
              <Footer />
            </div>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
